### PR TITLE
MRW updates to support LI 1XD configuration based power capping with FW1060

### PR DESCRIPTION
**Pull request by adangster**
Attributes added:
DEFAULT_MIN_PROC_POWER_PER_CHIP
	Default min proc power to use for power capping if MIN_PROC_POWER_PER_CHIP is not filled in from WOF table
MISC_POWER_PER_SYSTEM
	Fixed power to account for all non-processor, non-memory power of the system in watts

Wof File for 12BC :  Everest-MRW.WofSetBins.tar.gz
Improves power capping capability to allow customers with 12BC to set power caps appropriate to the specific module sort populated in the system.

### CODE REVIEW

**Review by dcrowell77 — APPROVED** [review]
Changes are fine

**Review by baileysh — COMMENTED** [review]
Looks good for format

**Comment by EricMarz** [comment]
Verified that Everest-MRW.WofSetBins.tar.gz contains the new WOF table with expanded header information in support of power capping.

**Comment by dcrowell77** [comment]
Known issues with the ubuntu build, merging this

**Pull request merged**
