### PR TITLE
DDR5 Support for Everest

### PR DESCRIPTION
**Pull request by adangster**
Based on Rainier change.

### CODE REVIEW

**Comment by mabaiocchi** [comment]
retest this please

**Comment by adangster** [comment]
hi, what is going on with this pull?  can someone help on why the build fail pls ?

**Comment by mabaiocchi** [comment]
I'm working on getting the details to see what needs to change for this to work on DDR5 systems.  I can also look into why it was breaking DDR4 systems.

**Comment by dcrowell77** [comment]
retest this please

**Comment by ruby452** [comment]
@adangster I reviewed this pending PR and there is a mistake in all the temp sensor I2C bus connections. You currently have them all (ts0, ts1 & ts2) going to the P10 I2C master and that's incorrect, they to go the OCMB i2c master target in the MRW which should be 'i2c-ocmb-master'.

**Comment by mabaiocchi** [comment]
retest this please

**Review by mabaiocchi — APPROVED** [review]
+1 review as I've seen this work on a DDR5 system (ever6bmc) and a DDR4 system (ever61bmc) with no obvious errors.

**Pull request merged**
