### PR TITLE
MRW updates for DDR5 DDIMM Power Curves per CQ 591648  

### PR DESCRIPTION
**Pull request by adangster**
MRW updates for DDR5 DDIMM Power Curves (for FW1060 or higher)
Change detail as request per https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=591648

### CODE REVIEW

**Review by dcrowell77 — APPROVED** [review]
Looks like a bunch of numbers that I don't understand so I'll assume you know what they are.

**Comment by adangster** [comment]
hi, I dont have permission to see the reason for is the  "IBM OP CI op-build build Ubuntu ppc64le — Build failed."   (no read permission)

can you some from admin check please?

**Comment by adangster** [comment]
> Looks like a bunch of numbers that I don't understand so I'll assume you know what they are.

yes, I just copy pasted the memory power limit values provided by the memory team.

**Comment by dcrowell77** [comment]
Looks like the job hit network/artifactory fails.  I'll retrigger the job.

**Comment by dcrowell77** [comment]
Appears to be some kind of a problem in the CI job related to the sbe-odyssey compile.  We were chasing issues with that last week so it might be related.

**Comment by dcrowell77** [comment]
Merging despite the ubuntu compile issues

**Pull request merged**
